=== ClimbsRocks/opendiversitydata/schema/eeo-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "opendiversitydata",
  "description": "JSON schema for U.S. EEO-1 survey data",
  "type": "object",
  "properties": {
    "meta": {
      "type": "object",
      "properties": { 
        "company": {
          "type": "string"
        }
      },
      "required": ["company"]
    },
    "section_a": {
      "type": "object",
      "properties": {
        "reporting_type": {
          "type": "string",
          "enum": [
            "Single-establishement Employer Report",
            "Consolidated Report",
            "Headquarters Unit Report",
            "Individual Establishment Report",
            "Special Report"
          ]
        }
      },
      "required": ["reporting_type"]
    },
    "section_b": {
      "type": "object",
      "properties": {
        "parent_company": {
          "type": "string"
        },
        "address": {
          "type": "object",
          "properties": {
            "street_address": { "type": "string" },
            "city": { "type": "string" },
            "state": {
              "type": "string",
              "enum": ["AL", "AK", "AS", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FM", "FL", "GA", "GU", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MH", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "MP", "OH", "OK", "OR", "PW", "PA", "PR", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VI", "VA", "WA", "WV", "WI", "WY"]
            },
            "zip_code": { "type": "string" }
          },
          "required": ["street_address", "city", "state", "zip_code"]
        },
        "previous_year_report": {
          "type": "boolean"
        }
      },
      "required": ["parent_company", "address", "previous_year_report"]
    },
    "section_c": {
      "type": "object",
      "properties": {
        "at_least_100": { "type": "boolean" },
        "affiliated": { "type": "boolean" },
        "DUNS": { "type": "boolean" }
      },
      "required": ["at_least_100", "affiliated", "DUNS"]
    }
  }
}

=== ClimbsRocks/opendiversitydata/json/dell.json
{
  "meta": { "company": "Dell" },
  "section_a": { "reporting_type": "Consolidated Report" },
  "section_b": {
    "parent_company": "DELL INC - (DELL USA) - ROUND ROCK",
    "address": {
      "street_address": "401 DELL WAY",
      "city": "ROUND ROCK",
      "state": "TX",
      "zip_code": "78682"
    },
    "previous_year_report": true
  },
  "section_c": {
    "at_least_100": true,
    "affiliated": false,
    "DUNS": true
  }
}
